### ISSUE TITLE
[Feature] Add NBT Support for Item Entries in JSON Format

### ISSUE THREAD

**Issue by Dragon-Seeker** [wisp-forest/CondensedCreativeItems#11]

**Comment by seriousfreezing** [comment]
I'll be interested to see when this feature is added!

**Comment by Dragon-Seeker** [comment]
Such a feature was added with 1.21 with the ability to parse stack objects within the `items` for a condensed entry

**Comment by Dragon-Seeker** [comment]
Added as of 1.21
