### ISSUE TITLE
[Bug] The next group does not move to the end of the previous open group.

### ISSUE THREAD

**Issue by seriousfreezing** [wisp-forest/CondensedCreativeItems#12]
![image](https://github.com/wisp-forest/condensed-creative/assets/66693072/256153e9-8478-47fb-b59d-05714fabfb9a)

The common and expected behavior even in the previous version (1.18.2) would be for the next group that is not open to be after the previous open group and not inside it.

**Comment by Dragon-Seeker** [comment]
Hopefully should be fixed with latest release

**Comment by seriousfreezing** [comment]
I've just tested it now and yes, it's been fixed successfully!
