### ISSUE TITLE
 [1.20.4][NeoForge] Crash on start due to networking error

### ISSUE THREAD

**Issue by ffuentesm** [wisp-forest/CondensedCreativeItems#14]
Loader:  neoforged:20.4.190
Mod version: condensed_creative-3.2.0+1.20.4-neoforge.jar

Due to new Updates on the Networking, this mod crashes the game on launch. 

Crash: https://mclo.gs/EESpk3Z
![image](https://github.com/wisp-forest/condensed-creative/assets/44974827/c7fb114b-1281-4174-982e-dd98936dd07e)

**Comment by Dragon-Seeker** [comment]
Actually, it's because I renamed the mixin config when I ported to neo and did not update such within the mods toml to the new file for some reason. Will have to look into this tomorrow
