### ISSUE TITLE
[1.20.4] Crash on NeoForge due to invalid mixins

### ISSUE THREAD

**Issue by ffuentesm** [wisp-forest/CondensedCreativeItems#15]
Loader: neoforged:20.4.232
Mod version: condensed_creative-3.2.1+1.20.4-neoforge.jar
https://mclo.gs/1fYfDyZ

I just updated the Mod, and seems the problem persists 
![image](https://github.com/wisp-forest/condensed-creative/assets/44974827/000c4091-4834-4dd6-a8a1-68047e943c8b)

**Comment by Dragon-Seeker** [comment]
Ok reuploaded it again... idk how but in dev nothing occurs for some reason

**Comment by Dragon-Seeker** [comment]
Furthermore testing has found that neo patches are going to screw a bit with some things so will need to release a new new version... dam it

**Comment by Dragon-Seeker** [comment]
Will need more time to deal with the latest neoforge version changes that are leading to general mixin issues within prod

**Comment by Dragon-Seeker** [comment]
Should be fixed and test such within production this time before a release
