### ISSUE TITLE
No stack numbers

### ISSUE THREAD

**Issue by iv8512** [wisp-forest/CondensedCreativeItems#17]
No stack sizes are shows when I open up the inventory in survival.

**Comment by Dragon-Seeker** [comment]
Ah that is my bad I have messed up the mixin on the fabric side leading to such count rendering never occurring, whoops. Will see about getting a fix for such out coming up

**Comment by Dragon-Seeker** [comment]
Pushed an update for such to Modrinth and Curseforge.
