### ISSUE TITLE
[Sugestion] Add better and/or official support for MoreCreativeTabs

### ISSUE THREAD

**Issue by DaRealSparky** [wisp-forest/CondensedCreativeItems#19]
So technically speaking, it does already work. However, getting the custom tabs to register with Condensed Creative requires a lot of long and tedious trial and error. I have been trying to set it up again, but I no longer have the resourcepack I created to make it happen the last time I used the mods together.

The biggest issue I am running into at the moment is that the ID's of the custom tabs are not straight-forward. One would assume the ID of a custom tab to be `"morecreativetabs:<tab_name_here>"` or `"<mod_name>:<tab_name_here>"`, with the second example referring to where in the resourcepack the custom tab file is located rather than a mods actual creative tab. 

The mod in question is this: [MoreCreativeTabs](https://www.curseforge.com/minecraft/mc-mods/morecreativetabs-forge-fabric)

<details>
<summary>Side Note</summary>
In Condensed Creative. it seems the ID's of the vanilla tabs the mod is using are the tabs names rather than their ID, for example: One might assume itemGroup.buildingBlocks would be minecraft:buildingBlocks for the ID of the tab in question. Instead, the ID used when making an entry is minecraft:building_blocks, which is different from how the ID of a mod's creative tab would work like itemGroup.tab1 and modname:tab1. Just something that seemed strange.
</details>

**Comment by Dragon-Seeker** [comment]
I don't know what to tell you that the ID's are not under my control but are done when the ItemGroup is registered. Mojang themselves does the Identifier for Building Blocks Group and overall the system within Condensed Creative uses the specific ItemGroup ID as the only proper way to target such.

**Comment by Dragon-Seeker** [comment]
It may be benifical to make a mod to add more tooltip information to ItemGroups when hovering over such within the Creative Screen allowing end users to better target which group is which rather than tring to track such down.

**Comment by Dragon-Seeker** [comment]
Overall as there is no direct incompatibility with [MoreCreativeTabs](https://www.curseforge.com/minecraft/mc-mods/morecreativetabs-forge-fabric) and such is more of an issue with finding tabs that could be handled by another mod.

**Comment by ildiem** [comment]
Hate to bump this but it's the only place I've seen someone in the same predicament I'm having right now; @DaRealSparky did you ever figure out what ID to use?

**Comment by DaRealSparky** [comment]
@ildiem Unfortunately not. I eventually started using MoreCreativeTabs to change the contents of the vanilla tabs as well as the tabs of other mods to achieve what I was going for. This way I can add items to the tabs and create entries for Condensed Creative for said existing tabs rather than making new tabs and entries at the same time. Not exactly what I had in mind, but the eventual outcome is the same.
