### ISSUE TITLE
The "+" icon is behind the inventory items

### ISSUE THREAD

**Issue by seriousfreezing** [wisp-forest/CondensedCreativeItems#20]
![image](https://github.com/user-attachments/assets/6f5a2dda-9df2-43ca-abb5-abe244a66620)

**Comment by Dragon-Seeker** [comment]
Can you send an instance of the log at all?

**Comment by seriousfreezing** [comment]
https://paste.atlauncher.com/view/c731f840-d70b-473e-9509-be9dfd44e681
[latest.log](https://github.com/user-attachments/files/16766698/latest.log)

**Comment by maevius669** [comment]
If you have **ImmersiveUI** installed, try setting `renderHotbarSelectorAboveItems: true` in its config file.

**Comment by seriousfreezing** [comment]
Fix: Disable ImmediatelyFast's “experimental_screen_batching” option.
