### ISSUE TITLE
[Support] Lack of documentation on how to use the mod

### ISSUE THREAD

**Issue by DaRealSparky** [wisp-forest/CondensedCreativeItems#6]
I am making a modpack and discovered this mod when looking for mods to improve aspects of the pack. However, creating custom entries is difficult without any sort of documentation, specifically the resource pack method. While there are example files in the mod and the source files in Github, these are not something everyone will be able follow if they don't know what they are doing.

**Comment by Dragon-Seeker** [comment]
Finally got around to implementing the Wiki on github and leaving a note about what version is being targeted for such.
