### ISSUE TITLE
[Incompatibility/bug] macOS inputs mod

### ISSUE THREAD

**Issue by Aces-and-Jacks** [wisp-forest/CondensedCreativeItems#7]
Make scrolling with touchpad not work correctly

https://mclo.gs/gBYRZSB

https://github.com/hamarb123/MCMacOSInputFixes/issues/10

**Comment by hamarb123** [comment]
Enabling discrete scrolling fixes this. This means that your mod @wisp-forest should ideally fix the code that receives scroll events by actually handling non-integer cases (like the base game does btw). And my mod needs to make trackpad scrolling work correctly with discrete scrolling enabled.

**Comment by Dragon-Seeker** [comment]
~~I don't quite understand the problem at hand. What happens with scrolling exactly that differs from standard Minecraft?~~

Nvm, I see a general Issue with scrolling that differs from Minecraft, Ill see what I can do about this.

**Comment by hamarb123** [comment]
On the base game when it receives a scroll event that is 0.1 for example, it will scroll down 0.1 of a item in the creative menu, rather than for example rounding it first.

**Comment by Dragon-Seeker** [comment]
Should be fixed in cc16987. Overall this was worse than I thought and was an overall scrolling bug, to say the least with how I handled values. I'm sorry for not getting this fix for some time as Life got in the way but I'll be getting this out later today.
